/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate_access.conf,v 1.12 2006/09/08 15:43:39 dts12 Exp $
 */
#ifndef SWRAIDMIB_H
#define SWRAIDMIB_H

/*
 * other required module components
 */
config_require(swRaidMIB_access)


/*
 * cache timeout
 */
#define SWRAID_CACHE_TIMEOUT	60


/*
 * function declarations 
 */
void                 init_swRaidMIB(void);
void                 initialize_table_swRaidTable(void);
Netsnmp_Node_Handler swRaidTable_handler;
Netsnmp_Node_Handler swRaidErrorFlag_handler;
Netsnmp_Node_Handler swRaidErrMessage_handler;


/*
 * OID numbers
 */
#define SWRAIDMIB_OID                1,3,6,1,4,1,2021,13,18
#define SWRAIDTABLE_OID              SWRAIDMIB_OID,1
#define SWRAIDERRORFLAG_OID          SWRAIDMIB_OID,100
#define SWRAIDERRMESSAGE_OID         SWRAIDMIB_OID,101


/*
 * column number definitions for table swRaidTable 
 */
#define COLUMN_SWRAIDINDEX		1
#define COLUMN_SWRAIDDEVICE		2
#define COLUMN_SWRAIDPERSONALITY	3
#define COLUMN_SWRAIDUNITS		4
#define COLUMN_SWRAIDUNITCOUNT		5
#define COLUMN_SWRAIDSTATUS		6

#define SWRAIDTABLE_MIN_COL   COLUMN_SWRAIDINDEX
#define SWRAIDTABLE_MAX_COL   COLUMN_SWRAIDSTATUS


#endif /** SWRAIDMIB_H */
