/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.access_functions.conf,v 1.9 2004/10/14 12:57:33 dts12 Exp $
 */
#ifndef SWRAIDMIB_ACCESS_H
#define SWRAIDMIB_ACCESS_H

/*
 * Maximum line size of input file
 */
#define MAX_LINE_SIZE	255


/*
 * enums for column swRaidStatus 
 */
#define RAIDSTATUSTC_INACTIVE		1
#define RAIDSTATUSTC_ACTIVE		2
#define RAIDSTATUSTC_FAULTY		3


/*
 * cache handlers
 */
extern int swRaidMIB_load(netsnmp_cache *cache, void *vmagic);
extern void swRaidMIB_free(netsnmp_cache *cache, void *magic);


/*
 * row level accessors for table swRaidTable
 */
extern Netsnmp_First_Data_Point  swRaidTable_get_first_data_point;
extern Netsnmp_Next_Data_Point   swRaidTable_get_next_data_point;


/*
 * column accessors for table swRaidTable
 */
extern long   *get_swRaidIndex(void *data_context, size_t *ret_len);
extern char   *get_swRaidDevice(void *data_context, size_t *ret_len);
extern char   *get_swRaidPersonality(void *data_context, size_t *ret_len);
extern char   *get_swRaidUnits(void *data_context, size_t *ret_len);
extern long   *get_swRaidUnitCount(void *data_context, size_t *ret_len);
extern long   *get_swRaidStatus(void *data_context, size_t *ret_len);


/*
 * scalar accessors
 */
extern long   *get_swRaidErrorFlag(size_t *ret_len);
extern char   *get_swRaidErrMessage(size_t *ret_len);

#endif                          /* SWRAIDMIB_ACCESS_H */
